### ISSUE TITLE
TypeError: document.getElementById(...) is null

### ISSUE THREAD

**Issue by jhgoebbert** [cmd-ntrf/jupyter-lmod#14] opened 2020-05-01 08:45 UTC
Hello,
when installing jupyter-lmod 0.5.0 in our jupyterlab 2.1 environment, we get the following error in the Web-konsole:  
`TypeError: document.getElementById(...) is null`
and the sidetab of jupyter-lmod is empty.

![jupyter-lmod_button-unload-unknown](https://user-images.githubusercontent.com/9266792/80793969-e9155280-8b98-11ea-985b-dff6915ce8ca.png)

**Comment by cmd-ntrf** [comment] 2020-05-01 11:18
The issue is fixed in this commit:
https://github.com/cmd-ntrf/jupyter-lmod/commit/4223b0c871f128e40c076640e1948d3b7249a5f0#diff-8578a0f958b5ffb1cdfb18f2777bea56

which Is not released. I will try to include it in 0.5.1 today.

**Comment by cmd-ntrf** [comment] 2020-05-01 14:32
Actually, the fix was part of 0.5.0. Can you check it is not a cache issue?

When I download, the jupyterlab-lmod 0.5.0 tarball from NPM, Lmod object is correctly initialized with `PageConfig` instead of `getElement.byId`
```
var lmod = new Lmod.Lmod(coreutils_1.PageConfig.getBaseUrl());
```

**Comment by jhgoebbert** [comment] 2020-05-01 16:24
You were right. Sorry, I was still using 0.3.0.  
But now I am on 0.5.0 and I get a new "TypeError document.getElementById(..) is null" in `refresh_avail_list()`  
![jupyter-lmod_element-modules](https://user-images.githubusercontent.com/9266792/80821418-f7835e80-8bd8-11ea-83ca-1946cc72ce20.png)

**Comment by cmd-ntrf** [comment] 2020-05-01 17:08
I have seen this, and (you can blame me) brush it off by refreshing the screen and it generally go away. But, clearly I should pay more attention to what is the issue and find a solution.

Can you confirm the problem go away when you refresh once... or frenetically?

**Comment by jhgoebbert** [comment] 2020-05-01 19:09
No, I can reload the webpage 10 times or more but the àvailable modules` stay empty and the error is always the same.

**Comment by cmd-ntrf** [comment] 2020-05-01 19:35
I am able to reproduce the issue of modules list staying empty even when refreshing the page when using Firefox instead of Chrome. I will make sure to test all browsers to find the right solution.

I will keep you updated.

**Comment by cmd-ntrf** [comment] 2020-05-04 04:42
After some refactoring, I think the problem is fixed.
Can you try https://www.npmjs.com/package/jupyterlab-lmod/v/0.6.0-beta.0 ?

**Comment by jhgoebbert** [comment] 2020-05-04 10:03
Yes, it is working. Great!
This was really a show-stopper for switching to JupyterLab 2 for us.

Thanks a lot for all your work and of course the fix. jupyter-lmod is a great plugin and essential for any JupyterHub+JupyterLab setup on a cluster with a lmod software module setup.

**Closed** 2020-05-05 12:40 UTC
Labels: bug
